# Generated by Django 4.2.11 on 2024-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_alter_post_name'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.ManyToManyField(related_name='tagged_files', to='post.tag'),
        ),
    ]
