# Generated by Django 4.2.11 on 2024-04-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_alter_userbadge_user'),
        ('post', '0025_alter_post_name'),
        ('file', '0005_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='user/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_files', to='user.profile')),
                ('download', models.ManyToManyField(blank=True, related_name='downloaded_files', to='user.profile')),
                ('downvote', models.ManyToManyField(blank=True, related_name='downvoted_files', to='user.profile')),
                ('save', models.ManyToManyField(blank=True, related_name='saved_files', to='user.profile')),
                ('tag', models.ManyToManyField(related_name='tagged_files', to='post.tag')),
                ('upvote', models.ManyToManyField(blank=True, related_name='upvoted_files', to='user.profile')),
            ],
        ),
    ]
