# Generated by Django 4.2.11 on 2024-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userbadge_user'),
        ('post', '0025_alter_post_name'),
        ('file', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='UserFile',
        ),
    ]
