# Generated by Django 4.2.11 on 2024-04-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_rename_file_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='download',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='save',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='upvote',
        ),
    ]
