# Generated by Django 4.2.11 on 2024-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userbadge_user'),
        ('file', '0008_remove_userfile_download_remove_userfile_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='download',
            field=models.ManyToManyField(blank=True, related_name='downloaded_files', to='user.profile'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvoted_files', to='user.profile'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='saved_files', to='user.profile'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvoted_files', to='user.profile'),
        ),
    ]
