# Generated by Django 4.2.11 on 2024-04-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_userfile_download_userfile_downvote_userfile_save_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='download',
            new_name='downloads',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='downvote',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='save',
            new_name='saves',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
