# Generated by Django 4.2.11 on 2024-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_userfile_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, upload_to='user/files/'),
        ),
    ]
