# Generated by Django 4.2.11 on 2024-03-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('post', '0003_alter_post_owner_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
