# Generated by Django 4.2.11 on 2024-03-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
        ('post', '0004_alter_post_owner_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner_content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner_object_id',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(related_name='downvoted_comments', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(related_name='upvoted_comments', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(related_name='downvoted_posts', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(related_name='upvoted_posts', to='user.profile'),
        ),
    ]
