# Generated by Django 4.2.11 on 2024-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_student_email'),
        ('post', '0018_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hashtags',
            field=models.ManyToManyField(related_name='tags', to='core.hashtag'),
        ),
    ]
