# Generated by Django 4.2.11 on 2024-04-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user'),
        ('core', '0005_organization_student_email'),
        ('post', '0019_tag_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.hashtag'),
        ),
    ]
