# Generated by Django 4.2.11 on 2024-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_tag_creator_alter_tag_hashtags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
