# Generated by Django 4.2.11 on 2024-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_total_points'),
        ('post', '0026_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(blank=True, to='user.profile'),
        ),
    ]
