# Generated by Django 4.2.11 on 2024-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=200)),
                ('badge_image', models.ImageField(upload_to='user/badge')),
                ('badge_descriptinon', models.TextField(max_length=500)),
            ],
        ),
    ]
