# Generated by Django 4.2.11 on 2024-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_badge_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='to',
            field=models.ManyToManyField(blank=True, related_name='badges', to='user.profile'),
        ),
    ]
