import random
import string
from django.core.management.base import BaseCommand
from post.models import Post
from user.models import Profile  # Replace 'your_app' with the name of your Django app
from django.utils.text import slugify

questions_data = [
    "How does the human brain process language?",
    "When did the Cold War end?",
    "Which is the fastest land animal?",
    "What are the benefits of learning a second language?",
    "How does the human muscular system work?",
    "Why are coral reefs important ecosystems?",
    "When was the theory of plate tectonics proposed?",
    "Which are the major functions of the liver?",
    "What are the effects of globalization on culture?",
    "How do antibiotics work to fight infections?",
    "Why do some people have phobias?",
    "When did the Great Depression begin?",
    "Which is the largest moon in the solar system?",
    "What are the causes of ocean pollution?",
    "How does the human endocrine system regulate hormones?",
    "Why do we have fingerprints?",
    "When was the theory of gravity proposed?",
    "Which are the main components of the nervous system?",
    "What are the effects of climate change on Arctic ecosystems?",
    "How do glaciers form?",
    "Why are wetlands important for the environment?",
    "When did the first modern humans appear?",
    "Which is the most densely populated country in the world?",
    "What are the benefits of renewable energy?",
    "How does the human excretory system remove waste?",
    "Why do we age?",
    "When was the first vaccine developed?",
    "Which are the major components of the solar system?",
    "What are the effects of pollution on marine life?",
    "How does the human reproductive system change with age?",
    "Why do some people have allergies?",
    "When did the concept of gravity originate?",
    "Which is the largest living organism on Earth?",
    "What are the consequences of air pollution on human health?",
    "How does the human immune system respond to infections?",
    "Why do we have dreams?",
    "When was the theory of evolution first proposed?",
    "Which are the major types of mental disorders?",
    "What are the effects of deforestation on indigenous communities?",
    "How does the human skeletal system support the body?",
    "Why are rainforests important for biodiversity?",
    "When was the first artificial satellite launched into space?",
    "Which is the longest mountain range in the world?",
    "What are the benefits of recycling?",
    "How does the human circulatory system transport nutrients?",
    "Why do some species go extinct?",
    "When did the first modern humans migrate out of Africa?",
    "Which is the deepest ocean trench in the world?",
    "What are the effects of ocean acidification on marine ecosystems?",
    "How does the human nervous system process information?",
    "Why do we experience emotions?",
    "When was the theory of relativity proposed?",
    "Which is the most abundant gas in the Earth's atmosphere?",
    "What are the effects of sleep deprivation on health?",
    "How do enzymes work in biological reactions?",
    "Why is the Amazon Rainforest important for biodiversity?",
    "When was the printing press invented?",
    "Which are the major types of cancer?",
    "What are the consequences of deforestation on wildlife?",
    "How does the human respiratory system function?",
    "Why do we experience deja vu?",
    "When did the Cold War end?",
    "Which is the fastest land animal?",
    "What are the benefits of learning a second language?",
    "How does the human muscular system work?",
    "Why are coral reefs important ecosystems?",
    "When was the theory of plate tectonics proposed?",
    "Which are the major functions of the liver?",
    "What are the effects of globalization on culture?",
    "How do antibiotics work to fight infections?",
    "Why do some people have phobias?",
    "When did the Great Depression begin?",
    "Which is the largest moon in the solar system?",
    "What are the causes of ocean pollution?",
    "How does the human endocrine system regulate hormones?",
    "Why do we have fingerprints?",
    "When was the theory of gravity proposed?",
    "Which are the main components of the nervous system?",
    "What are the effects of climate change on Arctic ecosystems?",
    "How do glaciers form?",
    "Why are wetlands important for the environment?",
    "When did the first modern humans appear?",
    "Which is the most densely populated country in the world?",
    "What are the benefits of renewable energy?",
    "How does the human excretory system remove waste?",
    "Why do we age?",
    "When was the first vaccine developed?",
    "Which are the major components of the solar system?",
    "What are the effects of pollution on marine life?",
    "How does the human reproductive system change with age?",
    "Why do some people have allergies?",
    "When did the concept of gravity originate?",
    "Which is the largest living organism on Earth?",
    "What are the consequences of air pollution on human health?",
    "How does the human immune system respond to infections?",
    "Why do we have dreams?",
    "When was the theory of evolution first proposed?",
    "Which are the major types of mental disorders?",
    "What are the effects of deforestation on indigenous communities?",
    "How does the human skeletal system support the body?",
    "Why are rainforests important for biodiversity?",
    "When was the first artificial satellite launched into space?",
    "Which is the longest mountain range in the world?",
    "What are the benefits of recycling?",
    "How does the human circulatory system transport nutrients?",
    "Why do some species go extinct?",
    "When did the first modern humans migrate out of Africa?",
    "Which is the deepest ocean trench in the world?",
    "What are the effects of ocean acidification on marine ecosystems?",
    "How does the human nervous system process information?",
    "Why do we experience emotions?",
]
question_descriptions = [
    "How does globalization affect culture, and what are the implications for cultural identity and diversity? In this question, we explore the complex interplay of globalization and cultural change, from the spread of Western media and consumerism to the rise of transnational identities and hybrid cultures. Through the lens of anthropology, sociology, and cultural studies, we examine the ways in which globalization reshapes cultural practices, beliefs, and values, raising questions about authenticity, tradition, and cultural heritage in an increasingly interconnected and diverse world.",
    "Why are bees important for ecosystems, and what are the threats to bee populations worldwide? In this question, we delve into the vital role of bees as pollinators, from honeybees and bumblebees to solitary bees and native pollinators. Through the lens of ecology, agriculture, and conservation biology, we examine the ecological significance of bees for plant reproduction and biodiversity, exploring the factors driving bee decline, from habitat loss and pesticide use to climate change and disease, and highlighting the urgent need for pollinator conservation and habitat restoration efforts.",
    "When did the Renaissance period begin, and what were its cultural, intellectual, and artistic achievements? In this question, we revisit the transformative era of the Renaissance, from the revival of classical learning and humanism to the flowering of art, literature, and science. Through the lens of history, art history, and intellectual history, we explore the cultural and social dynamics of the Renaissance, from the Medici family and the Sistine Chapel to the invention of the printing press and the spread of Renaissance ideals across Europe.",
    "Which is the tallest mountain outside of Asia, and what geological processes formed the world's tallest peaks? In this question, we explore the majestic heights of the Andes, the Rockies, and the Alps, from the summit of Mount Aconcagua to the peak of Mount McKinley. Through the lens of geology, plate tectonics, and mountain formation, we examine the forces that shape mountain landscapes, from continental collisions and volcanic eruptions to erosion and glaciation, shedding light on the geological history and natural beauty of Earth's highest peaks.",
    "What are the steps of the scientific method, and how do scientists use this framework to investigate and understand the natural world? In this question, we explore the principles of scientific inquiry, from observation and hypothesis testing to experimentation and data analysis. Through the lens of philosophy of science, epistemology, and research methodology, we examine the iterative process of scientific discovery, from formulating research questions and designing experiments to interpreting results and drawing conclusions, highlighting the importance of empirical evidence and peer review in advancing knowledge and understanding.",
    "How does the human digestive system work, and what role do digestive enzymes, hormones, and gut microbiota play in nutrient absorption and digestion? In this question, we explore the fascinating anatomy and physiology of the gastrointestinal tract, from the mouth and esophagus to the stomach, small intestine, and colon. Through the lens of human biology, physiology, and nutrition science, we examine the mechanisms of digestion and absorption, from mechanical breakdown and chemical digestion to nutrient transport and waste elimination, shedding light on the complex interplay of organs and systems that sustain life.",
    "Why do leaves change color in the fall, and what biological processes underlie this seasonal phenomenon? In this question, we explore the dazzling display of autumn foliage, from the vibrant reds and oranges to the golden yellows and purples. Through the lens of botany, plant physiology, and environmental science, we examine the physiological mechanisms of leaf pigmentation and senescence, from chlorophyll breakdown and carotenoid synthesis to environmental cues and photoperiodism, unraveling the mysteries of fall colors and their ecological significance.",
    "When was the Declaration of Independence signed, and what principles of liberty, equality, and democracy did it espouse? In this question, we revisit the historic moment when the American colonies declared their independence from British rule, laying the foundation for a new nation and a new era of democratic governance. Through the lens of history, political philosophy, and constitutional law, we examine the ideals and aspirations embodied in the Declaration of Independence, from natural rights and popular sovereignty to the social contract and the pursuit of happiness, exploring their enduring legacy and relevance in today's world.",
    "Which is the largest ocean on Earth, and what geological processes shape the vast expanse of the world's oceans? In this question, we explore the boundless depths of the Pacific Ocean, from the Mariana Trench to the Great Barrier Reef. Through the lens of oceanography, marine geology, and physical geography, we examine the forces that shape ocean basins, from seafloor spreading and subduction to wave dynamics and ocean currents, unraveling the mysteries of the deep and the vital role of oceans in regulating Earth's climate and sustaining life.",
    "What are the benefits of exercise for mental health, and how does physical activity promote emotional well-being and cognitive function? In this question, we explore the transformative power of exercise, from running and yoga to swimming and weightlifting. Through the lens of psychology, neuroscience, and sports medicine, we examine the physiological and psychological effects of physical activity on the brain and body, from endorphin release and stress reduction to neurogenesis and improved mood, highlighting the importance of regular exercise for mental health and overall well-being.",
    "How are languages formed and evolved, and what linguistic processes shape the diversity of human language? In this question, we explore the origins and evolution of language, from the dawn of human speech to the rich tapestry of languages spoken around the world today. Through the lens of linguistics, anthropology, and cognitive science, we examine the mechanisms of language change and variation, from phonological shifts and grammatical innovations to language contact and creolization, shedding light on the cultural, social, and cognitive factors that shape linguistic diversity and continuity.",
    "Why are rainforests called the lungs of the Earth, and what ecological services do they provide for the planet? In this question, we explore the lush biodiversity and vital ecosystem services of tropical rainforests, from the Amazon Basin to the Congo Basin. Through the lens of ecology, biogeochemistry, and conservation biology, we examine the role of rainforests in regulating climate, purifying air and water, and supporting millions of species, from plants and animals to indigenous communities and global economies, highlighting the urgent need for rainforest conservation and sustainable development.",
    "When was the first computer invented, and how has computing technology evolved over time? In this question, we trace the origins of computing from ancient abacuses and mechanical calculators to the digital computers and supercomputers of today. Through the lens of computer science, engineering, and innovation studies, we explore the key milestones and breakthroughs in the history of computing, from the Turing machine and the ENIAC to the personal computer and the internet, unraveling the transformative impact of technology on society, industry, and everyday life.",
    "Which countries are part of the G7, and what role do they play in shaping global politics, economics, and security? In this question, we explore the geopolitical dynamics of the Group of Seven, from the United States and Canada to Japan and Germany. Through the lens of international relations, diplomacy, and global governance, we examine the history and purpose of the G7, from its origins as an informal forum for economic cooperation to its role in addressing pressing global challenges, from climate change and pandemics to terrorism and economic inequality.",
    "What are the principles of democracy, and how do democratic systems of government differ from autocratic and authoritarian regimes? In this question, we explore the core tenets of democracy, from popular sovereignty and political equality to the rule of law and human rights. Through the lens of political philosophy, comparative politics, and constitutional law, we examine the institutions and practices of democratic governance, from free and fair elections to independent judiciaries and civil liberties, highlighting the importance of democratic norms and values in safeguarding individual freedoms and promoting collective welfare.",
    "How does the human eye perceive color, and what physiological and psychological processes underlie color vision? In this question, we explore the remarkable capabilities of the human visual system, from the retina and optic nerve to the visual cortex and beyond. Through the lens of neuroscience, physiology, and perceptual psychology, we examine the mechanisms of color perception, from the trichromatic theory and opponent-process theory to color constancy and cultural influences, shedding light on the intricate interplay of biology and culture in shaping our experience of color.",
    "When was the theory of relativity proposed, and how has it revolutionized our understanding of space, time, and gravity? In this question, we delve into the mind-bending concepts of Einstein's theory of relativity, from special relativity and time dilation to general relativity and gravitational waves. Through the lens of theoretical physics, cosmology, and philosophy of science, we explore the implications of relativity for our conception of the universe, from black holes and wormholes to the expanding cosmos and the fabric of spacetime, unraveling the mysteries of the cosmos and our place within it.",
    "Which are the major world religions, and how do they shape beliefs, values, and practices around the globe? In this question, we explore the diverse tapestry of religious traditions, from Christianity and Islam to Hinduism, Buddhism, and beyond. Through the lens of religious studies, anthropology, and sociology of religion, we examine the origins, doctrines, and rituals of the world's major faiths, exploring their historical development, cultural diversity, and contemporary significance in shaping individual and collective identities, ethics, and worldviews.",
    "What are the benefits of biodiversity for agriculture, and how can we promote sustainable farming practices that support ecosystem health and resilience? In this question, we explore the intricate relationship between biodiversity and agriculture, from pollination and pest control to soil fertility and climate resilience. Through the lens of agroecology, conservation biology, and sustainable development, we examine the ecological services provided by biodiversity for food production, from crop diversity and agroforestry to integrated pest management and regenerative agriculture, highlighting the importance of conserving and restoring biodiversity for the future of farming and food security.",
    "When was the theory of plate tectonics proposed, and how has it revolutionized our understanding of Earth's geology and geography? In this question, we explore the transformative insights of plate tectonics theory, from continental drift and seafloor spreading to subduction zones and mid-ocean ridges. Through the lens of geology, geophysics, and paleontology, we examine the mechanisms of plate motion and crustal deformation, from convergent and divergent boundaries to transform faults and hotspots, shedding light on the dynamic processes that shape the surface of our planet and drive geological hazards such as earthquakes and volcanic eruptions.",
    "Which is the largest rainforest in the world, and what ecological services does it provide for biodiversity, climate regulation, and indigenous cultures? In this question, we explore the breathtaking biodiversity and ecological significance of the Amazon Rainforest, from the canopy to the forest floor. Through the lens of ecology, conservation biology, and anthropology, we examine the rich tapestry of life in the Amazon, from jaguars and macaws to indigenous tribes and traditional knowledge, highlighting the urgent need for rainforest conservation and sustainable development in the face of deforestation, climate change, and biodiversity loss.",
    "What are the benefits of learning a second language, and how does bilingualism affect cognitive development, linguistic abilities, and cultural awareness? In this question, we explore the cognitive, social, and cultural advantages of multilingualism, from improved executive function and metalinguistic awareness to enhanced empathy and intercultural competence. Through the lens of psycholinguistics, sociolinguistics, and education research, we examine the neuroplasticity of the bilingual brain, from language acquisition and code-switching to language maintenance and revitalization, shedding light on the lifelong benefits of learning and using multiple languages in a globalized world.",
    "Why do some people experience deja vu, and what are the neurological and psychological mechanisms underlying this mysterious phenomenon? In this question, we explore the fascinating phenomenon of deja vu, from the subjective experience of familiarity to the cognitive and neural processes that give rise to it. Through the lens of cognitive psychology, neuroscience, and memory studies, we examine the theories and explanations for deja vu, from dual processing models and memory errors to temporal lobe epilepsy and dissociative experiences, shedding light on the mysteries of the mind and consciousness.",
    "When did the Cold War end, and what were the political, economic, and social consequences of this geopolitical rivalry between the United States and the Soviet Union? In this question, we revisit the tumultuous era of the Cold War, from the Berlin Wall and the Cuban Missile Crisis to the collapse of the Soviet Union and the end of bipolarity. Through the lens of diplomatic history, international relations, and political theory, we examine the ideological, military, and cultural dimensions of the Cold War, from containment and deterrence to détente and glasnost, exploring its lasting legacy and lessons for global peace and security in the 21st century.",
    "Which is the fastest land animal, and what adaptations enable it to achieve remarkable speeds in pursuit of prey? In this question, we explore the extraordinary athleticism and agility of the cheetah, the world's fastest land animal. Through the lens of biomechanics, physiology, and evolutionary biology, we examine the anatomical and physiological adaptations that allow cheetahs to sprint at speeds of up to 60 miles per hour, from elongated limbs and flexible spines to powerful muscles and specialized respiratory systems, shedding light on the evolutionary arms race between predators and prey in the African savanna.",
    "What are the consequences of deforestation on wildlife, and how does habitat loss threaten the survival of endangered species around the world? In this question, we explore the ecological impacts of deforestation, from the loss of habitat and biodiversity to the fragmentation of ecosystems and the spread of invasive species. Through the lens of conservation biology, ecology, and environmental policy, we examine the cascading effects of deforestation on wildlife populations, from habitat destruction and resource depletion to habitat fragmentation and edge effects, highlighting the urgent need for forest conservation and sustainable land management practices to protect biodiversity and ecosystem services.",
    "How does the human respiratory system function, and what physiological mechanisms enable us to breathe, oxygenate our blood, and remove carbon dioxide from our bodies? In this question, we explore the anatomy and physiology of the respiratory system, from the nasal cavity and trachea to the lungs and alveoli. Through the lens of human biology, physiology, and pulmonary medicine, we examine the mechanics of ventilation, gas exchange, and respiratory control, from inspiration and expiration to the regulation of blood pH and the role of respiratory diseases in disrupting normal lung function, shedding light on the vital importance of breathing for sustaining life and maintaining health.",
    "Why do we experience deja vu, and what are the cognitive and neurological mechanisms underlying this eerie sensation of familiarity? In this question, we delve into the mysteries of the mind and memory, exploring the subjective experience of deja vu and its underlying neural substrates. Through the lens of cognitive psychology, neuroscience, and memory studies, we examine the theories and explanations for deja vu, from memory retrieval errors and familiarity signals to temporal lobe epilepsy and dissociative experiences, shedding light on the complex interplay of perception, memory, and consciousness in shaping our subjective experience of reality.",
    "When did the theory of plate tectonics revolutionize our understanding of Earth's geology and geography, and how has it transformed our conception of continental drift, seafloor spreading, and crustal deformation? In this question, we explore the transformative insights of plate tectonics theory, from its early proponents like Alfred Wegener to the modern synthesis of geological evidence and geophysical models. Through the lens of geology, geophysics, and paleontology, we examine the mechanisms of plate motion and crustal deformation, from divergent and convergent boundaries to transform faults and hotspots, unraveling the mysteries of the dynamic processes that shape the surface of our planet and drive geological hazards such as earthquakes and volcanic eruptions.",
    "Which are the major world religions, and what beliefs, practices, and rituals characterize each religious tradition? In this question, we explore the diverse tapestry of religious faiths, from Christianity and Islam to Hinduism, Buddhism, and beyond. Through the lens of religious studies, anthropology, and cultural history, we examine the origins, doctrines, and rituals of the world's major religions, exploring their historical development, cultural diversity, and contemporary significance in shaping individual and collective identities, ethics, and worldviews.",
    "What are the benefits of learning a second language, and how does bilingualism affect cognitive development, linguistic abilities, and cultural awareness? In this question, we explore the cognitive, social, and cultural advantages of multilingualism, from improved executive function and metalinguistic awareness to enhanced empathy and intercultural competence. Through the lens of psycholinguistics, sociolinguistics, and education research, we examine the neuroplasticity of the bilingual brain, from language acquisition and code-switching to language maintenance and revitalization, shedding light on the lifelong benefits of learning and using multiple languages in a globalized world.",
    "Why do some people experience deja vu, and what are the cognitive and neurological mechanisms underlying this mysterious phenomenon? In this question, we explore the fascinating phenomenon of deja vu, from the subjective experience of familiarity to the cognitive and neural processes that give rise to it. Through the lens of cognitive psychology, neuroscience, and memory studies, we examine the theories and explanations for deja vu, from dual processing models and memory errors to temporal lobe epilepsy and dissociative experiences, shedding light on the mysteries of the mind and consciousness.",
    "When did the Cold War end, and what were the political, economic, and social consequences of this geopolitical rivalry between the United States and the Soviet Union? In this question, we revisit the tumultuous era of the Cold War, from the Berlin Wall and the Cuban Missile Crisis to the collapse of the Soviet Union and the end of bipolarity. Through the lens of diplomatic history, international relations, and political theory, we examine the ideological, military, and cultural dimensions of the Cold War, from containment and deterrence to détente and glasnost, exploring its lasting legacy and lessons for global peace and security in the 21st century.",
    "Which is the fastest land animal, and what adaptations enable it to achieve remarkable speeds in pursuit of prey? In this question, we explore the extraordinary athleticism and agility of the cheetah, the world's fastest land animal. Through the lens of biomechanics, physiology, and evolutionary biology, we examine the anatomical and physiological adaptations that allow cheetahs to sprint at speeds of up to 60 miles per hour, from elongated limbs and flexible spines to powerful muscles and specialized respiratory systems, shedding light on the evolutionary arms race between predators and prey in the African savanna.",
    "What are the consequences of deforestation on wildlife, and how does habitat loss threaten the survival of endangered species around the world? In this question, we explore the ecological impacts of deforestation, from the loss of habitat and biodiversity to the fragmentation of ecosystems and the spread of invasive species. Through the lens of conservation biology, ecology, and environmental policy, we examine the cascading effects of deforestation on wildlife populations, from habitat destruction and resource depletion to habitat fragmentation and edge effects, highlighting the urgent need for forest conservation and sustainable land management practices to protect biodiversity and ecosystem services.",
    "How does the human respiratory system function, and what physiological mechanisms enable us to breathe, oxygenate our blood, and remove carbon dioxide from our bodies? In this question, we explore the anatomy and physiology of the respiratory system, from the nasal cavity and trachea to the lungs and alveoli. Through the lens of human biology, physiology, and pulmonary medicine, we examine the mechanics of ventilation, gas exchange, and respiratory control, from inspiration and expiration to the regulation of blood pH and the role of respiratory diseases in disrupting normal lung function, shedding light on the vital importance of breathing for sustaining life and maintaining health."
]

class Command(BaseCommand):
    help = 'Populates the Post model with random questions'

    def handle(self, *args, **options):
        Post.objects.all().delete()  # Clear existing posts
        profiles = Profile.objects.all()
        for _ in range(20):
            owner = random.choice(profiles)
            question = random.choice(questions_data)
            description = random.choice(question_descriptions)
            slug = slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
            post = Post.objects.create(owner=owner, name=question, slug=slug, description=description)
            # Randomly assign video to some posts
            if random.random() < 0.2:  # 20% chance of having a video
                post.video = 'posts/videos/sample_video.mp4'  # Change path to your sample video file
                post.save()
            self.stdout.write(self.style.SUCCESS(f'Successfully created post "{post.name}"'))
        self.stdout.write(self.style.SUCCESS('Successfully populated Post model with random questions'))
