# Generated by Django 4.2.11 on 2024-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='organization/logo/'),
        ),
    ]
