# Generated by Django 4.2.11 on 2024-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
