# Generated by Django 4.2.11 on 2024-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_report_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='organization',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='organization',
            field=models.ManyToManyField(related_name='hashtags', to='core.organization'),
        ),
    ]
